blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://www.wowinterface.com/forums/forumdisplay.php?f=87
    about: Please ask and answer questions in the oUF section on wowinterface.com
